// <auto-generated />
namespace PetesPettingZoo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class displaynamesoncustomers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(displaynamesoncustomers));
        
        string IMigrationMetadata.Id
        {
            get { return "201710241358442_display names on customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
